```{r}
install.packages("ggplot2")
install.packages("matlib")
install.packages("rsample")
```
```{r}
X=as.matrix(read.csv(file="C:/Users/sanja/Downloads/X_1673241366257.csv",header = F))
colnames(X)<-c("X1","X2","X3","X4")
```

```{r}
Y=as.matrix(read.csv(file="C:/Users/sanja/Downloads/y_1673241374123.csv",header = F))
colnames(Y)<-c("Y")

```

```{r}
Time = read.csv("C:/Users/sanja/Downloads/time_1673241270748.csv", header = F, skip = 1)
Time = as.matrix(rbind(0, Time))

```

```{r}
X.ts<-ts(X,start = c(min(Time),max(Time)),frequency =1)
```
```{r}
Y.ts<-ts(Y,start = c(min(Time),max(Time)),frequency =1)

```

```{r}
plot(X.ts,main = "Time series plot of X Signal", xlab = "Time", ylab = "Input signal", col="darkviolet")
plot(Y.ts,main = "Time series plot of Y Signal", xlab = "Time", ylab = "Output signal", col="darkviolet")
```
```{r}
dis=density(X)
plot(dis,main = "Density plot of whole input signal", col="darkblue")
# Creating a Histrogram of X signal
hist(X,freq = FALSE,main = "Density Histogram", col = "coral")
#Adding density in the histogram
lines(dis,lwd=2,col="darkblue")
rug(jitter(X))
```
```{r}
dis_X1=density(X[,"X1"])
hist(X[,"X1"],freq = FALSE,main = "Histogram and density plot of X1",xlab = "X1 Signal", col = "coral")
lines(dis_X1,lwd=2,col="darkblue")
# Add the data-poins with noise in the X-axis
rug(jitter(X[,"X1"]))
```

```{r}
dis_X2=density(X[,"X2"])
hist(X[,"X2"],freq = FALSE,main = "Histogram and density plot of X2",xlab = "X2 Signal", col="coral")
lines(dis_X2,lwd=2,col="darkblue")
rug(jitter(X[,"X2"]))
#Creating a density if X3 signal
dis_X3=density(X[,"X3"])
hist(X[,"X3"],freq = FALSE,main = "Histogram and density plot of X3",xlab = "X3 Signal" , col="coral")
lines(dis_X3,lwd=2,col="darkblue")
rug(jitter(X[,"X3"]))
      
```

```{r}
dis_X4=density(X[,"X4"])
hist(X[,"X4"],freq = FALSE,main = "Histogram and density plot of X4",xlab = "X4 Signal", col = "coral")
lines(dis_X1,lwd=2,col="darkblue")
rug(jitter(X[,"X4"]))

```
```{r}
dis_y=density(Y)
plot(dis_y,main = "Density plot of Y",,xlab = "Output Signal", col="darkblue")
hist(Y,freq = FALSE,main = "Histogram and density plot of Y",xlab = "Output Signal", col="coral")
lines(dis_y,lwd=2,col="darkblue")
rug(jitter(Y))
```

```{r}
colors <- c("coral", # Orange
            "darkblue", # Light green
            "red") # Darker green

group <- group <- ifelse(X < 0, "Group 1",
                 ifelse(X > 1, "Group 2",
                        "Group 3"))

# Plotting X1 against Y
plot(X[,"X1"],Y,main = "Correlation betweeen X1 and Y signal", xlab = "X1 signal", ylab = "Output
signal",pch = 20,  col=colors[factor(group)]) 
# Plotting X2 against Y
plot(X[,"X2"],Y,main = "Correlation betweeen X2 and Y signal", xlab = "X2 signal", ylab = "Output
signal",pch = 20,  col=colors[factor(group)])
# Plotting X3 against Y
plot(X[,"X3"],Y,main = "Correlation betweeen X3 and Y signal", xlab = "X3 signal", ylab = "Output
signal",pch = 20,  col=colors[factor(group)])
# Plotting X4 against Y
plot(X[,"X4"],Y,main = "Correlation betweeen X4 and Y signal", xlab = "X4 signal", ylab = "Output
signal",pch = 20,  col=colors[factor(group)])

#plot(X[,"X4"],Y,main = "Correlation betweeen X4 and Y signal", xlab = "X4 signal", ylab = "Output signal", col="red")

```
```{r}
# Calculating ones for binding the data
ones = matrix(1 , length(X)/4,1)
ones
```
```{r}
#Calculating thetahat of Model 1
#Binding data from equation of model 1.
X_model1<-cbind(ones,(X[,"X4"]),(X[,"X1"])^2,(X[,"X1"])^3,(X[,"X3"])^4)
X_model1
#Calculating thetahat of model 1
Model1_thetahat=solve(t(X_model1) %*% X_model1) %*% t(X_model1) %*% Y
Model1_thetahat
```

```{r}
#Binding data from equation of model 2.
X_model2<-cbind(ones,(X[,"X3"])^3,(X[,"X3"])^4)
X_model2
#Calculating thetahat of Model 2
Model2_thetahat=solve(t(X_model2) %*% X_model2) %*% t(X_model2) %*% Y
Model2_thetahat
```
```{r}
#Binding data from equation of model 3.
X_model3<-cbind(ones,X[,"X2"],(X[,"X1"])^3,(X[,"X3"])^4)
X_model3
#Calculating thetahat of Model 3
Model3_thetahat=solve(t(X_model3) %*% X_model3) %*% t(X_model3) %*% Y
Model3_thetahat
```
```{r}
#For model 4
#Binding data from equation of model 4.
X_model4<-cbind(ones,X[,"X4"],X[,"X1"]^3,X[,"X3"]^4)
X_model4
#Calculating thetahat of Model 4
Model4_thetahat=solve(t(X_model4) %*% X_model4) %*% t(X_model4) %*% Y
Model4_thetahat

```
```{r}
#Binding data from equation of model 5.
X_model5<-cbind(ones,X[,"X4"],X[,"X1"]^2,X[,"X1"]^3,X[,"X3"]^4,X[,"X1"]^4)
X_model5
#Calculating thetahat of Model 5
Model5_thetahat=solve(t(X_model5) %*% X_model5) %*% t(X_model5) %*% Y
Model5_thetahat
```
```{r}
#Calculating Y-hat and RSS Model 1
Y_hat_m1 = X_model1 %*% Model1_thetahat
Y_hat_m1
#Calculating RSS
RSS_Model_1=sum((Y-Y_hat_m1)^2)
RSS_Model_1

```
```{r}
Y_hat_m2 = X_model2 %*% Model2_thetahat
Y_hat_m2
RSS_Model_2=sum((Y-Y_hat_m2)^2)
RSS_Model_2
```
```{r}
Y_hat_m3 = X_model3 %*% Model3_thetahat
Y_hat_m3
RSS_Model_3=sum((Y-Y_hat_m3)^2)
RSS_Model_3

```
```{r}
#Calculating Y-hat and RSS of model 4
Y_hat_m4 = X_model4 %*% Model4_thetahat
Y_hat_m4
RSS_Model_4=sum((Y-Y_hat_m4)^2)
RSS_Model_4

```
```{r}
#Calculating Y-hat and RSS of model 5
Y_hat_m5 = X_model5 %*% Model5_thetahat
Y_hat_m5
RSS_Model_5=sum((Y-Y_hat_m5)^2)
RSS_Model_5

```
```{r}
N=length(Y)
#Calculating the Variance of Model 1
Variance_model1=RSS_Model_1/(N-1)
Variance_model1
#Calculating the log-likelihood of Model 1
likehood_Model_1=
-(N/2)*(log(2*pi))-(N/2)*(log(Variance_model1))-(1/(2*Variance_model1))*RSS_Model_1
likehood_Model_1

```

```{r}
#Calculating Variance and log-likelihood of Model 2
Variance_model2=RSS_Model_2/(N-1)
Variance_model2

```
```{r}
likehood_Model_2=
-(N/2)*(log(2*pi))-(N/2)*(log(Variance_model2))-(1/(2*Variance_model2))*RSS_Model_2
likehood_Model_2

```

```{r}
#Calculating Variance and log-likelihood of Model 3
Variance_model3=RSS_Model_3/(N-1)
Variance_model3
likehood_Model_3=
-(N/2)*(log(2*pi))-(N/2)*(log(Variance_model3))-(1/(2*Variance_model3))*RSS_Model_3
likehood_Model_3
```
```{r}
#Calculating Variance and log-likelihood of Model 4
Variance_model4=RSS_Model_4/(N-1)
Variance_model4
likehood_Model_4=
-(N/2)*(log(2*pi))-(N/2)*(log(Variance_model4))-(1/(2*Variance_model4))*RSS_Model_4
likehood_Model_4
```

```{r}
#Calculating Variance and log-likelihood of Model 5
Variance_model5=RSS_Model_5/(N-1)
Variance_model5
likehood_Model_5=
-(N/2)*(log(2*pi))-(N/2)*(log(Variance_model5))-(1/(2*Variance_model5))*RSS_Model_5
likehood_Model_5

```
```{r}
##Calculating AIC and BIC of model 1
K_model1<-length(Model1_thetahat)
K_model1
AIC_model1=2*K_model1-2*likehood_Model_1
AIC_model1
BIC_model1=K_model1*log(N)-2*likehood_Model_1
BIC_model1

```

```{r}
## thetahat of model 2
K_model2<-length(Model2_thetahat)
K_model2
##Calculating AIC and BIC of model 2
AIC_model2=2*K_model2-2*likehood_Model_2
AIC_model2
BIC_model2=K_model2*log(N)-2*likehood_Model_2
BIC_model2
```

```{r}
## thetahat of model 3
K_model3<-length(Model3_thetahat)
K_model3
```

```{r}
##Calculating AIC and BIC of model 3
AIC_model3=2*K_model3-2*likehood_Model_3
AIC_model3
BIC_model3=K_model3*log(N)-2*likehood_Model_3
BIC_model3

```

```{r}
## thetahat of model 4
K_model4<-length(Model1_thetahat)
K_model4

```

```{r}
##Calculating AIC and BIC of model 4
AIC_model4=2*K_model4-2*likehood_Model_4
AIC_model4
BIC_model4=K_model4*log(N)-2*likehood_Model_4
BIC_model4
```

```{r}
## thetahat of model 5
K_model5<-length(Model5_thetahat)
K_model5
```
```{r}
##Calculating AIC and BIC of model 5
AIC_model5=2*K_model5-2*likehood_Model_5
AIC_model5
BIC_model5=K_model5*log(N)-2*likehood_Model_5
BIC_model5
```
```{r}
## Error of model1
model1_error <- Y-Y_hat_m1
## Plotting the graph QQplot and QQ line of model 1
qqnorm(model1_error, col = "coral",main = "QQ plot of model 1")
qqline(model1_error, col = "darkblue",lwd=1)
```
```{r}
## Error of model2
model2_error <- Y-Y_hat_m2 # error of model 2
## Plotting QQplot and QQ line of model 2
qqnorm(model2_error, col = "coral",main = "QQ plot of model 2")
qqline(model2_error, col = "darkblue")

```
```{r}
## Error of model3
model3_error <- Y- Y_hat_m3
## Plotting QQplot and QQ line of model 3
qqnorm(model3_error, col = "coral",main = "QQ plot of model 3")
qqline(model3_error, col = "darkblue")

```
```{r}
## Error of model4
model4_error <- Y-Y_hat_m4
## Plotting QQplot and QQ line of model 4
qqnorm(model4_error, col = "coral",main = "QQ plot of model 4")
qqline(model4_error, col = "darkblue")
```

```{r}
## Error of model5
model5_error <- Y- Y_hat_m5
## Plotting QQplot and QQ line of model 5
qqnorm(model5_error, col = "coral",main = "QQ plot of model 5")
qqline(model5_error, col = "darkblue")
```

```{r}
#split data x 
set.seed(123)

x_nrow = nrow(X) 

x_splitIndex <- sample(1:x_nrow, size = 0.7 * x_nrow , replace = FALSE) 
# Split the data into training and testing datasets
x_training_data <- X[x_splitIndex, ]
x_testing_data <- X[-x_splitIndex, ]


#split data y 
y_nrow = nrow(Y)
y_splitIndex <- sample(1:y_nrow, size = 0.7 * y_nrow , replace = FALSE) 
y_training_data <- Y[y_splitIndex, ] 
y_testing_data <- Y[-y_splitIndex, ]

```

```{r}
#Using Model number one task 2.7
#training
training_ones=matrix(1,length(x_training_data)/4,1)
testing_ones=matrix(1,length(x_testing_data)/4,1)

#random noise
noise_training = rnorm(length(x_training_data)/4, 0, 0.1)
noise_testing = rnorm(length(x_testing_data)/4, 0, 0.1)

training_x = cbind(training_ones, (x_training_data[,"X4"]), (x_training_data[,"X1"])**3 , (x_training_data[,"X2"])**4 , (x_training_data[,"X1"])**4 , noise_training)

training_theta_hat = solve(t(training_x) %*% training_x) %*% t(training_x) %*% y_training_data

training_theta_hat
```

```{r}
testing_x = cbind(testing_ones, (x_testing_data[,"X4"]), (x_testing_data[,"X1"])**3 , (x_testing_data[,"X2"])**4 , (x_testing_data[,"X1"])**4 , noise_testing)
```

```{r}
#Calculating Y-hat and Rss Model 1
testing_y_hat = testing_x %*% training_theta_hat

#RSS
training_error = y_testing_data-testing_y_hat
training_rss=sum((training_error)^2)
training_rss
```
```{r}
#for error bar calculation

conf_interval = t.test(y_training_data) #default 95% confidence interval
conf_interval_start = conf_interval$conf.int[1]
conf_interval_end = conf_interval$conf.int[2]
error_line = conf_interval$stderr

par(mar=c(5, 4, 4, 2) + 0.1)

plot(density(y_training_data), col="blue", lwd=2, main="Distribution of Training Data", 
     xlab="Value", ylab="Density")
abline(v=conf_interval_start,col="coral", lty=2) 
abline(v=conf_interval_end,col="darkgreen", lty=2)
abline(v=error_line,col="gray", lty=2)
```

```{r}
##Task 3
## Model 3 will be used, parameter are selected and kept constant.
arr_1=0
arr_2=0
f_value=0
s_value=0
Model3_thetahat
#values from thetahat
thetebias <- 0.448299550 #choosen parameter
thetaone <- 0.038109255 # chosen prarameter
thetatwo <- 0.009827804 # constant value
thetafour <- 0.002092558 # constant value
Epison <- RSS_Model_3 * 2 ## fixing value of eplision
num <- 100 #number of iteration
##Calculating Y-hat for performing rejection ABC
counter <- 0

for (i in 1:num) {
range1 <- runif(1,-0.448299550,0.448299550) # calculating the range
range1
range2 <- runif(1,-0.038109255,0.038109255)
New_thetahat <- matrix(c(range1,range2,thetatwo,thetafour))
New_Y_Hat <- X_model3 %*% New_thetahat ## New Y hat
new_RSS <- sum((Y-New_Y_Hat)^2)
new_RSS
if (new_RSS > Epison){
arr_1[i] <- range1
arr_2[i] <- range2
counter = counter+1
f_value <- matrix(arr_1)
s_value <- matrix(arr_2)
}
}
hist(f_value, col="coral")
hist(s_value, col = "coral")
###ploting the graph
plot(f_value,s_value, col = c("coral", "darkblue"), main = "Joint and Marginal Posterior Distribution")

```

